add festival

diff --git a/sysdev/bashrc b/sysdev/bashrc
--- a/sysdev/bashrc
+++ b/sysdev/bashrc
@@ -32,6 +32,9 @@ shopt -s histappend
 # check the window size after each command
 shopt -s checkwinsize
 
+# ignore simple spelling mistakes in the cd command
+shopt -s cdspell
+
 # make less more friendly
 [ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"
 
@@ -56,7 +59,7 @@ fi
 
 PS1="\[$txtwht\]\w\n${debian_chroot:+($debian_chroot)}\\
 ┌────[\[$txtgrn\]\u@\h\[$txtwht\]]──[\[$txtylw\]\W\[$txtwht\]] \n\\
-\[$bakwht\] \[$txtwht\]\$([[ \$? == 0 ]] && echo \" \[$bakgrn\] \" || echo \" \[$bakred\] \") \\
+\[$bakwht\] \[$txtwht\]\$([[ \$? == 0 ]] && echo \" \[$bakgrn\] \" || (echo \" \[$bakred\] \" ; echo 'error' | festival --tts)) \\
 \[$txtwht\]\n\\
 └─────\[$txtrst\]>>> "
 
@@ -74,5 +77,6 @@ fi
 clear
 echo -e "${txtcyn}"
 figlet "Welcome $USER"
+echo -e "welcome $USER" | festival --tts
 echo -e "${txtrst}"
 
